import { Toaster } from 'react-hot-toast';
import AllOverlay from './components/AllOverlay';
import UserProvider from './context/user'
import './globals.css';
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'TikTok Clone',
  description: 'Generated by Hasan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
      <body>
      <AllOverlay />
      {children}
      <Toaster />
      </body>
      </UserProvider>
    </html>
  )
}
